"""Files other than pages: the footer and structured-data partials, and the RSS feed."""

import html
import re
from datetime import datetime, timezone
from email.utils import format_datetime

from .config import DOCS, ROOT, SITE_URL, fail
from .icons import ICONS
from .images import thumb
from .ledger import Record
from .news import KIND_LABELS, NewsItem
from .people import Person
from .structured import organization, to_json
from .text import esc, is_external

FEED_ITEMS = 30


def write_footer(site: Record, affiliations: list[Record]) -> None:
    """overrides/partials/cm-footer.html from data/site.yaml and the current
    affiliations (links go through the template's url filter, so they work
    from every page)."""
    def u(path: str) -> str:
        return path if is_external(path) else "{{ '" + path + "' | url }}"

    for s in site["social"]:
        if s["icon"] not in ICONS:
            fail(f"data/site.yaml social {s['label']!r}: icon must be one of {sorted(ICONS)}")
    logos = "".join(
        f'<li><a href="{esc(a["url"])}" title="{esc(a["name"])}"><img src="{u(thumb(a.get("logo_dark") or a["logo"], 300))}" '
        f'alt="{esc(a["name"])}" loading="lazy"></a></li>' for a in affiliations)
    social = "".join(f'<li><a href="{esc(s["url"])}">{ICONS[s["icon"]]}<span>{esc(s["label"])}</span></a></li>'
                     for s in site["social"])
    address = "<br>".join(esc(x) for x in site["contact"]["address"])
    out = f"""{{#- Generated by scripts/build_pages.py from data/site.yaml - edit that file instead. -#}}
<footer class="cm-footer">
  <div class="cm-footer__inner">
    <div class="cm-footer__col">
      <p class="cm-footer__title">{esc(site["name"])}</p>
      <p>{esc(site["motto"])}</p>
      <img class="cm-footer__logo" src="{u(thumb(site["footer_logo"], 500))}" alt="Cell Migration – Jacquemet Lab logo" loading="lazy">
    </div>
    <div class="cm-footer__col">
      <p class="cm-footer__title">Affiliations</p>
      <ul class="cm-footer__logos">{logos}</ul>
    </div>
    <div class="cm-footer__col">
      <p class="cm-footer__title">Get in touch</p>
      <ul class="cm-footer__social">{social}</ul>
      <p class="cm-footer__address">{address}</p>
    </div>
  </div>
  <div class="cm-footer__bottom">
    <span>{{{{ config.copyright }}}}</span>
    <span><a href="{u('feed.xml')}">RSS</a> · <a href="{{{{ config.repo_url }}}}">Website source on GitHub</a></span>
  </div>
</footer>
"""
    (ROOT / "overrides" / "partials" / "cm-footer.html").write_text(out, encoding="utf-8")


def write_feed(site: Record, news: list[NewsItem]) -> None:
    """RSS of the newest news items: docs/feed.xml, and docs/feed/index.html
    (the old WordPress feed address). pubDate only when the day is known."""
    items = []
    for n in news[:FEED_ITEMS]:
        url = n["url"] if n["url"] and n["url"].startswith("http") else SITE_URL + (n["url"] or f"news/#y{n['date'][:4]}")
        when = ""
        if n["precision"] == "day":
            day = datetime.strptime(n["date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
            when = f"<pubDate>{format_datetime(day)}</pubDate>"
        text = re.sub(r"<[^>]+>", "", n["html"])
        items.append(f"<item><title>{esc(KIND_LABELS[n['kind']] + ': ' + n['title'])}</title><link>{esc(url)}</link>"
                     f"<guid isPermaLink=\"false\">{esc(n['kind'] + ':' + n['date'] + ':' + n['title'])}</guid>"
                     f"{when}<description>{esc(html.unescape(text))}</description></item>")
    rss = ('<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel>'
           f'<title>{esc(site["name"])}: news</title><link>{SITE_URL}news/</link>'
           f'<atom:link href="{SITE_URL}feed.xml" rel="self" type="application/rss+xml"/>'
           f'<description>{esc(site["motto"])}</description><language>en</language>'
           + "".join(items) + "</channel></rss>\n")
    (DOCS / "feed.xml").write_text(rss, encoding="utf-8")
    (DOCS / "feed").mkdir(exist_ok=True)
    (DOCS / "feed" / "index.html").write_text(rss, encoding="utf-8")


def write_jsonld(site: Record, affiliations: list[Record], members: list[Person], leader_bio: str) -> None:
    """overrides/partials/cm-jsonld.html: the lab as schema.org JSON-LD, on every page."""
    data = organization(site, affiliations, members, thumb(site["footer_logo"], 500), leader_bio)
    (ROOT / "overrides" / "partials" / "cm-jsonld.html").write_text(
        "{#- Generated by scripts/build_pages.py (structured.py) - do not edit. -#}\n"
        f'<script type="application/ld+json">{to_json(data)}</script>\n', encoding="utf-8")
