"""Files other than pages: the footer partial and the RSS feed."""

from datetime import datetime, timezone
from email.utils import format_datetime

from .config import DOCS, ROOT, SITE_URL, fail
from .featured import Story
from .icons import ICONS
from .images import thumb
from .ledger import Record
from .text import esc, is_external, md

FEED_ITEMS = 30


def write_footer(site: Record, affiliations: list[Record]) -> None:
    """overrides/partials/cm-footer.html from data/site.yaml and the current
    affiliations (links go through the template's url filter, so they work
    from every page)."""
    def u(path: str) -> str:
        return path if is_external(path) else "{{ '" + path + "' | url }}"

    for s in site["social"]:
        if s["icon"] not in ICONS:
            fail(f"data/site.yaml social {s['label']!r}: icon must be one of {sorted(ICONS)}")
    logos = "".join(
        f'<li><a href="{esc(a["url"])}" title="{esc(a["name"])}"><img src="{u(thumb(a.get("logo_dark") or a["logo"], 300))}" '
        f'alt="{esc(a["name"])}" loading="lazy"></a></li>' for a in affiliations)
    social = "".join(f'<li><a href="{esc(s["url"])}">{ICONS[s["icon"]]}<span>{esc(s["label"])}</span></a></li>'
                     for s in site["social"])
    address = "<br>".join(esc(x) for x in site["contact"]["address"])
    out = f"""{{#- Generated by scripts/build_pages.py from data/site.yaml - edit that file instead. -#}}
<footer class="cm-footer">
  <div class="cm-footer__inner">
    <div class="cm-footer__col">
      <p class="cm-footer__title">{esc(site["name"])}</p>
      <p>{esc(site["motto"])}</p>
      <img class="cm-footer__logo" src="{u(thumb(site["footer_logo"], 500))}" alt="Cell Migration – Jacquemet Lab logo" loading="lazy">
    </div>
    <div class="cm-footer__col">
      <p class="cm-footer__title">Affiliations</p>
      <ul class="cm-footer__logos">{logos}</ul>
    </div>
    <div class="cm-footer__col">
      <p class="cm-footer__title">Get in touch</p>
      <ul class="cm-footer__social">{social}</ul>
      <p class="cm-footer__address">{address}</p>
    </div>
  </div>
  <div class="cm-footer__bottom">
    <span>{{{{ config.copyright }}}}</span>
    <span><a href="{u('feed.xml')}">RSS</a> · <a href="{{{{ config.repo_url }}}}">Website source on GitHub</a></span>
  </div>
</footer>
"""
    (ROOT / "overrides" / "partials" / "cm-footer.html").write_text(out, encoding="utf-8")


def write_feed(site: Record, featured: list[Story]) -> None:
    """RSS of the newest featured papers: docs/feed.xml, and docs/feed/index.html
    (the old WordPress feed address). pubDate only when the exact date is known."""
    items = []
    for s in featured[:FEED_ITEMS]:
        url = SITE_URL + f'portfolio/{s["slug"]}/'
        when = ""
        if s["date"]:
            day = datetime.strptime(s["date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
            when = f"<pubDate>{format_datetime(day)}</pubDate>"
        items.append(f"<item><title>{esc(s['title'])}</title><link>{url}</link><guid>{url}</guid>"
                     f"{when}<description>{esc(md(s['summary']))}</description></item>")
    rss = ('<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel>'
           f'<title>{esc(site["name"])}</title><link>{SITE_URL}</link>'
           f'<atom:link href="{SITE_URL}feed.xml" rel="self" type="application/rss+xml"/>'
           f'<description>{esc(site["motto"])}</description><language>en</language>'
           + "".join(items) + "</channel></rss>\n")
    (DOCS / "feed.xml").write_text(rss, encoding="utf-8")
    (DOCS / "feed").mkdir(exist_ok=True)
    (DOCS / "feed" / "index.html").write_text(rss, encoding="utf-8")
