"""Generate the website pages from the files in data/.

    python scripts/build_pages.py     (then: zensical build / zensical serve)

Reads                                        Writes (git-ignored, rebuilt every time)
  data/site.yaml                               docs/index.md (home), footer
  data/research.yaml                           docs/research.md
  data/things_done/lab_members.yaml            docs/lab-members.md,
    + data/members/, data/photos/, team.yaml     docs/assets/images/members/ (photos)
  data/things_done/software.yaml               docs/software.md
    + data/software.yaml
  data/things_done/publications.yaml           docs/publications.md,
    + data/featured.yaml                         docs/featured-research.md, docs/portfolio/<slug>.md
  data/things_done/datasets.yaml               docs/datasets.md
  data/things_done/ (papers, coauthors,        docs/lab-in-numbers.md
    preprint lag, metrics, software,
    datasets, lab members)
  data/gallery.yaml                            docs/gallery.md
  data/talks.yaml                              docs/online-lectures.md
  data/things_done/ (papers, software,         docs/feed.xml and docs/feed/index.html
    datasets)                                    (RSS of research outputs)
  data/site.yaml + affiliations, members       overrides/partials/cm-footer.html, cm-jsonld.html
  data/previews.yaml                           link previews (title, text, picture) of every page
  content/*.md                                 docs/about-us.md, docs/join-us.md, docs/licensing.md
  (all of the above)                           docs/llms.txt, docs/llms-full.txt (Markdown for LLMs)
                                               docs/assets/thumbs/ (resized images, kept)

data/things_done/ is copied from the things_done ledger by
scripts/sync_things_done.py; change the ledger, not those files. Anything
missing or inconsistent stops the build with a message naming the file to
fix. Page addresses match the old WordPress site, so old links keep working.
The code is in scripts/cellmig/ (see its __init__.py for a map).
"""

import shutil

from cellmig.config import DATA, DOCS, GENERATED, load
from cellmig.featured import load_featured
from cellmig.ledger import Ledger, affiliation_list, support_list
from cellmig.llms import write_llms
from cellmig.outputs import build_outputs
from cellmig.pages_content import (
    page_datasets,
    page_gallery,
    page_handwritten,
    page_research,
    page_software,
    page_talks,
)
from cellmig.pages_home import page_home
from cellmig.pages_numbers import page_numbers
from cellmig.pages_papers import page_featured, page_publications
from cellmig.pages_people import page_members
from cellmig.people import lab_names, leader, load_members
from cellmig import rights
from cellmig.previews import check_all_used
from cellmig.profile import pi_profile
from cellmig.site_files import write_feed, write_footer, write_jsonld
from cellmig.structured import plain


def clean() -> None:
    """Delete the pages generated by the previous run (not the thumbnail cache)."""
    for name in GENERATED:
        path = DOCS / name
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def main() -> None:
    """Build every generated page from data/."""
    clean()
    site = load(DATA / "site.yaml")
    ledger = Ledger()
    members = load_members()
    lab = lab_names(members)
    featured = load_featured(ledger)
    affiliations = affiliation_list(site["affiliations"], ledger)
    funding = support_list(site["funding"], site["programmes"], ledger)

    outputs = build_outputs(ledger, featured)
    page_home(site, featured, funding)
    page_research(ledger)
    page_members(members)
    page_software(ledger, featured)
    page_featured(featured, ledger, lab)
    page_numbers(ledger, lab, members)
    page_publications(ledger, featured, lab, leader(members))
    page_datasets(ledger, site)
    page_gallery()
    page_talks()
    page_handwritten("about-us", extra=pi_profile(ledger.profile, leader(members)))
    page_handwritten("join-us")
    page_handwritten("licensing")
    write_feed(site, outputs)
    write_footer(site, affiliations)
    write_jsonld(site, affiliations, members, plain(ledger.profile["short_bio"]), funding)
    write_llms(site, featured, ledger, members, affiliations, funding)
    check_all_used()
    rights.use_theme_images()      # favicon, touch icon, default preview image
    rights.check_all_recorded()   # every image shown has a rights entry (data/media.yaml)
    print(f"Generated pages: {len(featured)} featured papers, {len(ledger.grouped())} publications, "
          f"{len(ledger.datasets)} datasets, {len(members)} people.")


if __name__ == "__main__":
    main()
