"""Generate the website pages from the files in data/.

    python scripts/build_pages.py     (then: zensical build / zensical serve)

Reads                                        Writes (git-ignored, rebuilt every time)
  data/site.yaml                               docs/index.md (home), footer, RSS feed
  data/research.yaml                           docs/research.md
  data/things_done/lab_members.yaml            docs/lab-members.md
    + data/members/, data/photos/, team.yaml
  data/things_done/software.yaml               docs/software.md
    + data/software.yaml
  data/things_done/publications.yaml           docs/publications.md,
    + data/featured.yaml                         docs/featured-research.md, docs/portfolio/<slug>.md
  data/things_done/datasets.yaml               docs/datasets.md
  data/things_done/ (all of it)                docs/lab-in-numbers.md
  data/gallery.yaml                            docs/gallery.md
  data/talks.yaml                              docs/online-lectures.md
                                               docs/feed.xml, docs/feed/index.html (RSS)
                                               overrides/partials/cm-footer.html, cm-jsonld.html
  data/previews.yaml                           link previews (title, text, picture) of every page
  content/*.md                                 docs/about-us.md, docs/image-analysis.md
  (all of the above)                           docs/llms.txt, docs/llms-full.txt (Markdown for LLMs)
                                               docs/assets/thumbs/ (resized images, kept)

data/things_done/ is copied from the things_done ledger by
scripts/sync_things_done.py; change the ledger, not those files. Anything
missing or inconsistent stops the build with a message naming the file to
fix. Page addresses match the old WordPress site, so old links keep working.
The code is in scripts/cellmig/ (see its __init__.py for a map).
"""

import shutil
from datetime import date

from cellmig.config import DATA, DOCS, GENERATED, load
from cellmig.featured import load_featured
from cellmig.ledger import Ledger, affiliation_list, funding_list
from cellmig.llms import write_llms
from cellmig.pages_content import (
    page_datasets,
    page_gallery,
    page_handwritten,
    page_research,
    page_software,
    page_talks,
)
from cellmig.pages_home import page_home
from cellmig.pages_numbers import page_numbers
from cellmig.pages_papers import page_featured, page_publications
from cellmig.pages_people import page_members
from cellmig.people import lab_names, load_members
from cellmig.previews import check_all_used
from cellmig.profile import pi_profile
from cellmig.site_files import write_feed, write_footer, write_jsonld


def clean() -> None:
    """Delete the pages generated by the previous run (not the thumbnail cache)."""
    for name in GENERATED:
        path = DOCS / name
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def main() -> None:
    """Build every generated page from data/."""
    clean()
    site = load(DATA / "site.yaml")
    ledger = Ledger()
    members = load_members()
    lab = lab_names(members)
    featured = load_featured(ledger)
    affiliations = affiliation_list(site["affiliations"], ledger)
    funding = funding_list(site["funding"], ledger, date.today().isoformat())

    page_home(site, featured, ledger, lab, affiliations, funding)
    page_research(ledger)
    page_members(members)
    page_software(ledger)
    page_featured(featured, ledger, lab)
    page_numbers(ledger, lab, members)
    page_publications(ledger, featured, lab)
    page_datasets(ledger, site)
    page_gallery()
    today = date.today()
    page_talks(ledger, today)
    leader = next(m for m in members if m["group"] == "pi" and m["status"] == "current")
    page_handwritten("about-us", extra=pi_profile(ledger.profile, leader))
    page_handwritten("image-analysis")
    write_feed(site, featured)
    write_footer(site, affiliations)
    write_jsonld(site, affiliations, members, ledger.profile["short_bio"])
    write_llms(site, featured, ledger, members, affiliations)
    check_all_used()
    print(f"Generated pages: {len(featured)} featured papers, {len(ledger.grouped())} publications, "
          f"{len(ledger.datasets)} datasets, {len(members)} people.")


if __name__ == "__main__":
    main()
