"""Copy the public part of the things_done ledger into data/things_done/.

    python scripts/sync_things_done.py --ledger ../things_done

Reads (in the things_done checkout):
  ledger/publications/<year>.yaml     papers and preprints
  ledger/registries/software.yaml     software projects
  ledger/registries/datasets.yaml     datasets

Writes (committed to this repository, read by scripts/build_pages.py):
  data/things_done/publications.yaml
  data/things_done/software.yaml
  data/things_done/datasets.yaml

Only fields that are already public (title, authors, venue, DOI, links,
descriptions) are copied. Everything else in the ledger - supervision,
roles, notes, conflict-of-interest data, author-position bookkeeping - is
never read, so it cannot end up on the website.

The things_done repository runs this script after every push (see
integrations/things_done/update-website.yml), so the website stays in sync
without the website ever needing access to the private ledger.
"""

import argparse
import html
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "things_done"

PUBLICATION_FIELDS = (
    "doi", "year", "type", "status", "title", "authors", "venue",
    "abstract", "peer_reviewed", "open_access_status", "related_dois",
)
SOFTWARE_FIELDS = (
    "id", "title", "status", "start_date", "repository_url", "github_repo_url",
    "description", "related_publication_dois",
)
DATASET_FIELDS = (
    "id", "title", "status", "dataset_type", "start_date", "repository_url",
    "archive_doi", "description", "dataset_tags", "related_publication_dois",
)


def load(path):
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def clean_text(value):
    """Crossref abstracts come with JATS tags (<jats:p>...); keep plain text."""
    value = re.sub(r"<[^>]+>", " ", str(value or ""))
    value = html.unescape(value)
    value = re.sub(r"^\s*(Abstract|Summary)\b[:.]?\s*", "", value, flags=re.I)
    return re.sub(r"\s+", " ", value).strip()


def pick(record, fields):
    out = {}
    for key in fields:
        value = record.get(key)
        if value in (None, "", []):
            continue
        out[key] = value
    return out


def publications(ledger):
    records = []
    for path in sorted((ledger / "ledger" / "publications").glob("[0-9]*.yaml")):
        for rec in load(path).get("records") or []:
            if not rec.get("doi") or not rec.get("title"):
                continue
            item = pick(rec, PUBLICATION_FIELDS)
            item["title"] = clean_text(item["title"])
            if "abstract" in item:
                item["abstract"] = clean_text(item["abstract"])
            records.append(item)
    records.sort(key=lambda r: (-int(r.get("year") or 0), r["title"].casefold()))
    return records


def registry(ledger, name, fields):
    data = load(ledger / "ledger" / "registries" / f"{name}.yaml")
    out = [pick(r, fields) for r in data.get("records") or [] if r.get("title")]
    out.sort(key=lambda r: (-int(str(r.get("start_date") or "0")[:4] or 0), r["title"].casefold()))
    return out


def dump(name, records, source):
    OUT.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by scripts/sync_things_done.py from things_done/{source}.\n"
        "# Do not edit by hand: change the ledger instead, the website updates itself.\n"
    )
    body = yaml.safe_dump({"records": records}, allow_unicode=True, sort_keys=False, width=100)
    (OUT / f"{name}.yaml").write_text(header + body, encoding="utf-8")
    print(f"{name}: {len(records)} records")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ledger", required=True, type=Path, help="path to a things_done checkout")
    ledger = parser.parse_args().ledger.resolve()
    if not (ledger / "ledger").is_dir():
        raise SystemExit(f"{ledger} does not look like a things_done checkout (no ledger/ folder)")
    dump("publications", publications(ledger), "ledger/publications")
    dump("software", registry(ledger, "software", SOFTWARE_FIELDS), "ledger/registries/software.yaml")
    dump("datasets", registry(ledger, "datasets", DATASET_FIELDS), "ledger/registries/datasets.yaml")


if __name__ == "__main__":
    main()
