"""Copy the public part of the things_done ledger into data/things_done/.

    python scripts/sync_things_done.py --ledger ../things_done

Reads (in the things_done checkout):
  ledger/publications/<year>.yaml     papers and preprints
  ledger/registries/software.yaml     software projects
  ledger/registries/datasets.yaml     datasets

Writes (committed to this repository, read by scripts/build_pages.py):
  data/things_done/publications.yaml
  data/things_done/software.yaml
  data/things_done/datasets.yaml
  data/things_done/dates.yaml   day-precision dates of preprint/journal pairs
                                (for the preprint-to-publication lag)
  data/things_done/authors.yaml co-authors' institutions and countries, per DOI,
                                from OpenAlex (for the collaborators page)

Dates and affiliations are looked up online once per DOI and cached, so a
normal sync only fetches what is new (use --offline to skip lookups).

Only fields that are already public (title, authors, venue, DOI, links,
descriptions) are copied. Everything else in the ledger - supervision,
roles, notes, conflict-of-interest data, author-position bookkeeping - is
never read, so it cannot end up on the website.

The things_done repository runs this script after every push (see
integrations/things_done/update-website.yml), so the website stays in sync
without the website ever needing access to the private ledger.
"""

import argparse
import html
import json
import re
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "things_done"

PUBLICATION_FIELDS = (
    "doi", "year", "type", "status", "title", "authors", "venue",
    "abstract", "peer_reviewed", "open_access_status", "related_dois",
    "featured", "issued_date",
)
SOFTWARE_FIELDS = (
    "id", "title", "status", "start_date", "repository_url", "github_repo_url",
    "description", "related_publication_dois",
)
DATASET_FIELDS = (
    "id", "title", "status", "dataset_type", "start_date", "repository_url",
    "archive_doi", "description", "dataset_tags", "related_publication_dois",
)


def load(path):
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def clean_text(value):
    """Crossref abstracts come with JATS tags (<jats:p>...); keep plain text."""
    value = re.sub(r"<[^>]+>", " ", str(value or ""))
    value = html.unescape(value)
    value = re.sub(r"^\s*(Abstract|Summary)\b[:.]?\s*", "", value, flags=re.I)
    return re.sub(r"\s+", " ", value).strip()


def pick(record, fields):
    out = {}
    for key in fields:
        value = record.get(key)
        if value in (None, "", []):
            continue
        out[key] = value
    return out


def publications(ledger):
    records = []
    for path in sorted((ledger / "ledger" / "publications").glob("[0-9]*.yaml")):
        for rec in load(path).get("records") or []:
            if not rec.get("doi") or not rec.get("title"):
                continue
            item = pick(rec, PUBLICATION_FIELDS)
            item["title"] = clean_text(item["title"])
            if "abstract" in item:
                item["abstract"] = clean_text(item["abstract"])
            records.append(item)
    records.sort(key=lambda r: (-int(r.get("year") or 0), r["title"].casefold()))
    return records


def registry(ledger, name, fields):
    data = load(ledger / "ledger" / "registries" / f"{name}.yaml")
    out = [pick(r, fields) for r in data.get("records") or [] if r.get("title")]
    out.sort(key=lambda r: (-int(str(r.get("start_date") or "0")[:4] or 0), r["title"].casefold()))
    return out


def dump(name, records, source):
    OUT.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by scripts/sync_things_done.py from things_done/{source}.\n"
        "# Do not edit by hand: change the ledger instead, the website updates itself.\n"
    )
    body = yaml.safe_dump({"records": records}, allow_unicode=True, sort_keys=False, width=100)
    (OUT / f"{name}.yaml").write_text(header + body, encoding="utf-8")
    print(f"{name}: {len(records)} records")


def csl_date(doi):
    """Posting date of a preprint / first publication date of an article, from
    the DOI's own metadata (works for Crossref and DataCite DOIs)."""
    req = urllib.request.Request(
        f"https://doi.org/{doi}",
        headers={"Accept": "application/vnd.citationstyles.csl+json",
                 "User-Agent": "cellmig-website (mailto:guillaume.jacquemet@abo.fi)"})
    with urllib.request.urlopen(req, timeout=20) as r:
        data = json.load(r)
    for key in ("posted", "published-online", "published-print", "issued", "created"):
        parts = (data.get(key) or {}).get("date-parts") or [[]]
        if len(parts[0]) == 3:
            return "%04d-%02d-%02d" % tuple(parts[0])
    return None


def dates(records, offline=False):
    """Dates for every preprint that has a journal version. The ledger's
    `issued_date` wins; other dates are looked up once and cached."""
    path = OUT / "dates.yaml"
    cache = (load(path).get("dates") or {}) if path.exists() else {}
    by_doi = {r["doi"].lower(): r for r in records}
    wanted = set()
    for r in records:
        if r.get("status") != "preprint":
            continue
        for d in r.get("related_dois") or []:
            other = by_doi.get(str(d).lower())
            if other and other.get("status") in ("published", "in_press"):
                wanted.update({r["doi"].lower(), other["doi"].lower()})
    out, fetched = {}, 0
    for doi in sorted(wanted):
        rec = by_doi[doi]
        if rec.get("issued_date"):
            out[doi] = str(rec["issued_date"])
        elif doi in cache:
            out[doi] = cache[doi]
        elif not offline:
            try:
                value = csl_date(rec["doi"])
            except Exception as err:  # network hiccup: try again next time
                print(f"  could not get date for {doi}: {err}")
                value = None
            if value:
                out[doi] = value
                fetched += 1
    body = yaml.safe_dump({"dates": out}, sort_keys=True)
    path.write_text("# Generated by scripts/sync_things_done.py (DOI metadata, cached).\n" + body, encoding="utf-8")
    print(f"dates: {len(out)} of {len(wanted)} ({fetched} looked up)")


def openalex_authors(doi):
    url = (f"https://api.openalex.org/works/doi:{doi}?select=authorships"
           "&mailto=guillaume.jacquemet@abo.fi")
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "cellmig-website"}), timeout=20) as r:
        data = json.load(r)
    out = []
    for a in data.get("authorships") or []:
        person = {"name": (a.get("author") or {}).get("display_name")}
        orcid = (a.get("author") or {}).get("orcid")
        if orcid:
            person["orcid"] = orcid.rsplit("/", 1)[-1]
        inst = [{"name": i["display_name"], "country": i.get("country_code")}
                for i in a.get("institutions") or [] if i.get("display_name")]
        if inst:
            person["institutions"] = inst[:2]
        if person["name"]:
            out.append(person)
    return out


def authors(records, offline=False):
    """Co-author affiliations per DOI, cached. A preprint is skipped when its
    journal version is in the ledger (same authors)."""
    path = OUT / "authors.yaml"
    cache = (load(path).get("works") or {}) if path.exists() else {}
    by_doi = {x["doi"].lower(): x for x in records}
    out, fetched = {}, 0
    for r in records:
        if r.get("status") == "preprint" and any(
                (by_doi.get(str(d).lower()) or {}).get("status") in ("published", "in_press")
                for d in r.get("related_dois") or []):
            continue
        doi = r["doi"].lower()
        if doi in cache:
            out[doi] = cache[doi]
        elif not offline:
            try:
                out[doi] = openalex_authors(r["doi"])
                fetched += 1
            except Exception as err:
                print(f"  no OpenAlex record for {doi}: {err}")
    body = yaml.safe_dump({"works": out}, allow_unicode=True, sort_keys=True, width=120)
    path.write_text("# Generated by scripts/sync_things_done.py (OpenAlex authorships, cached).\n" + body, encoding="utf-8")
    print(f"authors: {len(out)} works ({fetched} looked up)")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ledger", required=True, type=Path, help="path to a things_done checkout")
    parser.add_argument("--offline", action="store_true", help="do not look up missing dates online")
    args = parser.parse_args()
    ledger = args.ledger.resolve()
    if not (ledger / "ledger").is_dir():
        raise SystemExit(f"{ledger} does not look like a things_done checkout (no ledger/ folder)")
    pubs = publications(ledger)
    dump("publications", pubs, "ledger/publications")
    dates(pubs, offline=args.offline)
    authors(pubs, offline=args.offline)
    dump("software", registry(ledger, "software", SOFTWARE_FIELDS), "ledger/registries/software.yaml")
    dump("datasets", registry(ledger, "datasets", DATASET_FIELDS), "ledger/registries/datasets.yaml")


if __name__ == "__main__":
    main()
